// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymutzwtyjjefcesmumhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltdXR6d3R5amplZmNlc211bWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MzE1OTksImV4cCI6MjA1OTUwNzU5OX0.0_eqvNp9Ok-Sn4Um8Tci_KUwl7XFO4fjHeG6nnqPBtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);